
<main class='mx-auto w-screen max-w-xl pt-8 px-4 flex flex-col justify-center items-center'>
	<a href='/' sveltekit:prefetch class='clickable transition sticky top-6 bg-primary rounded shadow p-2 mr-auto'> Back </a>

	<h1 class='text-8xl font-black mb-8'> Pistol </h1>
	<p>
		Pistol is an open source speedcubing timer that brings a modern aproach and desing. 
	</p>
	<p>
		Focused on the best possible user expirience: elegancy, simplicity, ease of use, performance and customization.
	</p>
	
	<h2 class='text-2xl mt-4'> Contributing </h2>
	<p>
		If you found a typo or a easy issue to fix, feel free to raise a new issue. I will fix it if it's reasonable or I will close it if it's not.
	</p>
	<p>
		Pistol is an <a href="https://github.com/Odilf/Pistol" target="_blank"> open source project</a>. If anyone wants to implement a new feature or to make changes in the code themselves, I will gladly review and merge pull requests. Just don't expect me to make the development process easier (I have no clue what I would be suppossed to do).
	</p>

	<h2 class='text-2xl mt-4'> Credits </h2>
	<p>
		All the cubing visualizations were made with <a href="https://github.com/cubing/cubing.js">cubing.js</a>.
	</p>
	<p>
		Scrambles for 3x3, 2x2, 4x4, 5x5, Pyrmanix, Square-1, Clock and Skewb are generated by the <a href="https://github.com/cs0x7f/cstimer">csTimer</a> scrambler, with modifications by lgarron for the <a href="https://github.com/cubing/timer">cubing.js timer</a>.
	</p>
	<p>
		Timer inspired mainly by <a href="https://csTimer.net">csTimer</a> and partialy by the <a href="https://timer.cubing.net">cubing.js timer</a>.
	</p>

	<h2 class='text-2xl mt-4'> License </h2>
	<p>
		This project is licensed under the GPL license (version 3 or later). This means that this library is free to use, although you must publish any code that uses it (e.g. also put it on GitHub). See the full license for exact details.
	</p>
</main>

<style lang='postcss'>
	p {
		@apply mb-4;
	}

	a {
		@apply text-secondary underline;
	}
</style>